# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.materials import Materials  # noqa: E501
from swagger_client.rest import ApiException


class TestMaterials(unittest.TestCase):
    """Materials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaterials(self):
        """Test Materials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.materials.Materials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
