# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.frame_analysis_details import FrameAnalysisDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestFrameAnalysisDetails(unittest.TestCase):
    """FrameAnalysisDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFrameAnalysisDetails(self):
        """Test FrameAnalysisDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.frame_analysis_details.FrameAnalysisDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
