# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.camera_api import CameraApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCameraApi(unittest.TestCase):
    """CameraApi unit test stubs"""

    def setUp(self):
        self.api = CameraApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_camera_set_origin_orientation_put(self):
        """Test case for camera_set_origin_orientation_put

        """
        pass

    def test_camera_state_get(self):
        """Test case for camera_state_get

        """
        pass

    def test_camera_state_put(self):
        """Test case for camera_state_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
