# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gui_api import GUIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGUIApi(unittest.TestCase):
    """GUIApi unit test stubs"""

    def setUp(self):
        self.api = GUIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_control_gui_detection_area_visibility_get(self):
        """Test case for control_gui_detection_area_visibility_get

        """
        pass

    def test_control_gui_detection_area_visibility_post(self):
        """Test case for control_gui_detection_area_visibility_post

        """
        pass

    def test_control_gui_detection_bounding_box_visibility_get(self):
        """Test case for control_gui_detection_bounding_box_visibility_get

        """
        pass

    def test_control_gui_detection_bounding_box_visibility_post(self):
        """Test case for control_gui_detection_bounding_box_visibility_post

        """
        pass

    def test_control_gui_detection_color_get(self):
        """Test case for control_gui_detection_color_get

        """
        pass

    def test_control_gui_detection_color_post(self):
        """Test case for control_gui_detection_color_post

        """
        pass

    def test_control_gui_detection_polygon_visibility_get(self):
        """Test case for control_gui_detection_polygon_visibility_get

        """
        pass

    def test_control_gui_detection_polygon_visibility_post(self):
        """Test case for control_gui_detection_polygon_visibility_post

        """
        pass

    def test_control_gui_detection_text_visibility_get(self):
        """Test case for control_gui_detection_text_visibility_get

        """
        pass

    def test_control_gui_detection_text_visibility_post(self):
        """Test case for control_gui_detection_text_visibility_post

        """
        pass

    def test_control_gui_detections_visibility_get(self):
        """Test case for control_gui_detections_visibility_get

        """
        pass

    def test_control_gui_detections_visibility_post(self):
        """Test case for control_gui_detections_visibility_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
