# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.inspection_api import InspectionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInspectionApi(unittest.TestCase):
    """InspectionApi unit test stubs"""

    def setUp(self):
        self.api = InspectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inspection_damage_added_post(self):
        """Test case for inspection_damage_added_post

        """
        pass

    def test_inspection_run_begin_pause_put(self):
        """Test case for inspection_run_begin_pause_put

        """
        pass

    def test_inspection_run_end_pause_put(self):
        """Test case for inspection_run_end_pause_put

        """
        pass

    def test_inspection_run_get(self):
        """Test case for inspection_run_get

        """
        pass

    def test_inspection_run_start_put(self):
        """Test case for inspection_run_start_put

        """
        pass

    def test_inspection_run_stop_put(self):
        """Test case for inspection_run_stop_put

        """
        pass

    def test_inspection_section_data_get(self):
        """Test case for inspection_section_data_get

        """
        pass

    def test_inspection_section_data_put(self):
        """Test case for inspection_section_data_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
