# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_api import DeviceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_control_device_restart_post(self):
        """Test case for control_device_restart_post

        """
        pass

    def test_control_device_shutdown_post(self):
        """Test case for control_device_shutdown_post

        """
        pass

    def test_web_hook_delete(self):
        """Test case for web_hook_delete

        """
        pass

    def test_web_hook_detection_updates_post(self):
        """Test case for web_hook_detection_updates_post

        """
        pass

    def test_web_hook_get(self):
        """Test case for web_hook_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
