# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.analysis_api import AnalysisApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalysisApi(unittest.TestCase):
    """AnalysisApi unit test stubs"""

    def setUp(self):
        self.api = AnalysisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analysis_results_current_get(self):
        """Test case for analysis_results_current_get

        """
        pass

    def test_analysis_results_details_current_get(self):
        """Test case for analysis_results_details_current_get

        """
        pass

    def test_analysis_results_details_mask_get(self):
        """Test case for analysis_results_details_mask_get

        """
        pass

    def test_analysis_results_inspection_log_get(self):
        """Test case for analysis_results_inspection_log_get

        """
        pass

    def test_analysis_video_resolution_get(self):
        """Test case for analysis_video_resolution_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
