# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Color(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'r': 'int',
        'g': 'int',
        'b': 'int',
        'a': 'int'
    }

    attribute_map = {
        'r': 'r',
        'g': 'g',
        'b': 'b',
        'a': 'a'
    }

    def __init__(self, r=None, g=None, b=None, a=None):  # noqa: E501
        """Color - a model defined in Swagger"""  # noqa: E501
        self._r = None
        self._g = None
        self._b = None
        self._a = None
        self.discriminator = None
        self.r = r
        self.g = g
        self.b = b
        if a is not None:
            self.a = a

    @property
    def r(self):
        """Gets the r of this Color.  # noqa: E501

        Red [0-255]  # noqa: E501

        :return: The r of this Color.  # noqa: E501
        :rtype: int
        """
        return self._r

    @r.setter
    def r(self, r):
        """Sets the r of this Color.

        Red [0-255]  # noqa: E501

        :param r: The r of this Color.  # noqa: E501
        :type: int
        """
        if r is None:
            raise ValueError("Invalid value for `r`, must not be `None`")  # noqa: E501

        self._r = r

    @property
    def g(self):
        """Gets the g of this Color.  # noqa: E501

        Green [0-255]  # noqa: E501

        :return: The g of this Color.  # noqa: E501
        :rtype: int
        """
        return self._g

    @g.setter
    def g(self, g):
        """Sets the g of this Color.

        Green [0-255]  # noqa: E501

        :param g: The g of this Color.  # noqa: E501
        :type: int
        """
        if g is None:
            raise ValueError("Invalid value for `g`, must not be `None`")  # noqa: E501

        self._g = g

    @property
    def b(self):
        """Gets the b of this Color.  # noqa: E501

        Blue [0-255]  # noqa: E501

        :return: The b of this Color.  # noqa: E501
        :rtype: int
        """
        return self._b

    @b.setter
    def b(self, b):
        """Sets the b of this Color.

        Blue [0-255]  # noqa: E501

        :param b: The b of this Color.  # noqa: E501
        :type: int
        """
        if b is None:
            raise ValueError("Invalid value for `b`, must not be `None`")  # noqa: E501

        self._b = b

    @property
    def a(self):
        """Gets the a of this Color.  # noqa: E501

        Alpha [0-255]  # noqa: E501

        :return: The a of this Color.  # noqa: E501
        :rtype: int
        """
        return self._a

    @a.setter
    def a(self, a):
        """Sets the a of this Color.

        Alpha [0-255]  # noqa: E501

        :param a: The a of this Color.  # noqa: E501
        :type: int
        """

        self._a = a

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Color, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Color):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
