# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DetectionState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detection_class': 'DetectionClasses',
        'path_position': 'float',
        'detection_id': 'str',
        'path_position_min': 'float',
        'path_position_max': 'float',
        'clock_position_min': 'float',
        'clock_position_max': 'float',
        'inspection_code': 'str',
        'c1': 'str',
        'c2': 'str'
    }

    attribute_map = {
        'detection_class': 'detectionClass',
        'path_position': 'pathPosition',
        'detection_id': 'detectionId',
        'path_position_min': 'pathPositionMin',
        'path_position_max': 'pathPositionMax',
        'clock_position_min': 'clockPositionMin',
        'clock_position_max': 'clockPositionMax',
        'inspection_code': 'inspectionCode',
        'c1': 'c1',
        'c2': 'c2'
    }

    def __init__(self, detection_class=None, path_position=None, detection_id=None, path_position_min=None, path_position_max=None, clock_position_min=None, clock_position_max=None, inspection_code=None, c1=None, c2=None):  # noqa: E501
        """DetectionState - a model defined in Swagger"""  # noqa: E501
        self._detection_class = None
        self._path_position = None
        self._detection_id = None
        self._path_position_min = None
        self._path_position_max = None
        self._clock_position_min = None
        self._clock_position_max = None
        self._inspection_code = None
        self._c1 = None
        self._c2 = None
        self.discriminator = None
        self.detection_class = detection_class
        if path_position is not None:
            self.path_position = path_position
        if detection_id is not None:
            self.detection_id = detection_id
        if path_position_min is not None:
            self.path_position_min = path_position_min
        if path_position_max is not None:
            self.path_position_max = path_position_max
        if clock_position_min is not None:
            self.clock_position_min = clock_position_min
        if clock_position_max is not None:
            self.clock_position_max = clock_position_max
        if inspection_code is not None:
            self.inspection_code = inspection_code
        if c1 is not None:
            self.c1 = c1
        if c2 is not None:
            self.c2 = c2

    @property
    def detection_class(self):
        """Gets the detection_class of this DetectionState.  # noqa: E501


        :return: The detection_class of this DetectionState.  # noqa: E501
        :rtype: DetectionClasses
        """
        return self._detection_class

    @detection_class.setter
    def detection_class(self, detection_class):
        """Sets the detection_class of this DetectionState.


        :param detection_class: The detection_class of this DetectionState.  # noqa: E501
        :type: DetectionClasses
        """
        if detection_class is None:
            raise ValueError("Invalid value for `detection_class`, must not be `None`")  # noqa: E501

        self._detection_class = detection_class

    @property
    def path_position(self):
        """Gets the path_position of this DetectionState.  # noqa: E501

        Weglaenge in [m]  # noqa: E501

        :return: The path_position of this DetectionState.  # noqa: E501
        :rtype: float
        """
        return self._path_position

    @path_position.setter
    def path_position(self, path_position):
        """Sets the path_position of this DetectionState.

        Weglaenge in [m]  # noqa: E501

        :param path_position: The path_position of this DetectionState.  # noqa: E501
        :type: float
        """

        self._path_position = path_position

    @property
    def detection_id(self):
        """Gets the detection_id of this DetectionState.  # noqa: E501

        Internal ID of found detection  # noqa: E501

        :return: The detection_id of this DetectionState.  # noqa: E501
        :rtype: str
        """
        return self._detection_id

    @detection_id.setter
    def detection_id(self, detection_id):
        """Sets the detection_id of this DetectionState.

        Internal ID of found detection  # noqa: E501

        :param detection_id: The detection_id of this DetectionState.  # noqa: E501
        :type: str
        """

        self._detection_id = detection_id

    @property
    def path_position_min(self):
        """Gets the path_position_min of this DetectionState.  # noqa: E501

        Weglaenge Beginn Zustand in [m]  # noqa: E501

        :return: The path_position_min of this DetectionState.  # noqa: E501
        :rtype: float
        """
        return self._path_position_min

    @path_position_min.setter
    def path_position_min(self, path_position_min):
        """Sets the path_position_min of this DetectionState.

        Weglaenge Beginn Zustand in [m]  # noqa: E501

        :param path_position_min: The path_position_min of this DetectionState.  # noqa: E501
        :type: float
        """

        self._path_position_min = path_position_min

    @property
    def path_position_max(self):
        """Gets the path_position_max of this DetectionState.  # noqa: E501

        Weglaenge ende Zustand in [m]  # noqa: E501

        :return: The path_position_max of this DetectionState.  # noqa: E501
        :rtype: float
        """
        return self._path_position_max

    @path_position_max.setter
    def path_position_max(self, path_position_max):
        """Sets the path_position_max of this DetectionState.

        Weglaenge ende Zustand in [m]  # noqa: E501

        :param path_position_max: The path_position_max of this DetectionState.  # noqa: E501
        :type: float
        """

        self._path_position_max = path_position_max

    @property
    def clock_position_min(self):
        """Gets the clock_position_min of this DetectionState.  # noqa: E501

        Uhrzeit von [1-12]  # noqa: E501

        :return: The clock_position_min of this DetectionState.  # noqa: E501
        :rtype: float
        """
        return self._clock_position_min

    @clock_position_min.setter
    def clock_position_min(self, clock_position_min):
        """Sets the clock_position_min of this DetectionState.

        Uhrzeit von [1-12]  # noqa: E501

        :param clock_position_min: The clock_position_min of this DetectionState.  # noqa: E501
        :type: float
        """

        self._clock_position_min = clock_position_min

    @property
    def clock_position_max(self):
        """Gets the clock_position_max of this DetectionState.  # noqa: E501

        Uhrzeit bis [1-12]  # noqa: E501

        :return: The clock_position_max of this DetectionState.  # noqa: E501
        :rtype: float
        """
        return self._clock_position_max

    @clock_position_max.setter
    def clock_position_max(self, clock_position_max):
        """Sets the clock_position_max of this DetectionState.

        Uhrzeit bis [1-12]  # noqa: E501

        :param clock_position_max: The clock_position_max of this DetectionState.  # noqa: E501
        :type: float
        """

        self._clock_position_max = clock_position_max

    @property
    def inspection_code(self):
        """Gets the inspection_code of this DetectionState.  # noqa: E501

        Haupt-Kode / Inspektions-Kode  # noqa: E501

        :return: The inspection_code of this DetectionState.  # noqa: E501
        :rtype: str
        """
        return self._inspection_code

    @inspection_code.setter
    def inspection_code(self, inspection_code):
        """Sets the inspection_code of this DetectionState.

        Haupt-Kode / Inspektions-Kode  # noqa: E501

        :param inspection_code: The inspection_code of this DetectionState.  # noqa: E501
        :type: str
        """

        self._inspection_code = inspection_code

    @property
    def c1(self):
        """Gets the c1 of this DetectionState.  # noqa: E501

        Charakterisierung 1  # noqa: E501

        :return: The c1 of this DetectionState.  # noqa: E501
        :rtype: str
        """
        return self._c1

    @c1.setter
    def c1(self, c1):
        """Sets the c1 of this DetectionState.

        Charakterisierung 1  # noqa: E501

        :param c1: The c1 of this DetectionState.  # noqa: E501
        :type: str
        """

        self._c1 = c1

    @property
    def c2(self):
        """Gets the c2 of this DetectionState.  # noqa: E501

        Charakterisierung 2  # noqa: E501

        :return: The c2 of this DetectionState.  # noqa: E501
        :rtype: str
        """
        return self._c2

    @c2.setter
    def c2(self, c2):
        """Sets the c2 of this DetectionState.

        Charakterisierung 2  # noqa: E501

        :param c2: The c2 of this DetectionState.  # noqa: E501
        :type: str
        """

        self._c2 = c2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetectionState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetectionState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
