# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FrameTime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'str',
        'frame_no': 'int'
    }

    attribute_map = {
        'time': 'time',
        'frame_no': 'frameNo'
    }

    def __init__(self, time=None, frame_no=None):  # noqa: E501
        """FrameTime - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._frame_no = None
        self.discriminator = None
        if time is not None:
            self.time = time
        if frame_no is not None:
            self.frame_no = frame_no

    @property
    def time(self):
        """Gets the time of this FrameTime.  # noqa: E501

        UTM  # noqa: E501

        :return: The time of this FrameTime.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this FrameTime.

        UTM  # noqa: E501

        :param time: The time of this FrameTime.  # noqa: E501
        :type: str
        """

        self._time = time

    @property
    def frame_no(self):
        """Gets the frame_no of this FrameTime.  # noqa: E501


        :return: The frame_no of this FrameTime.  # noqa: E501
        :rtype: int
        """
        return self._frame_no

    @frame_no.setter
    def frame_no(self, frame_no):
        """Sets the frame_no of this FrameTime.


        :param frame_no: The frame_no of this FrameTime.  # noqa: E501
        :type: int
        """

        self._frame_no = frame_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FrameTime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FrameTime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
