# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GuiDetectionColorBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detection_class': 'DetectionClasses',
        'color': 'Color'
    }

    attribute_map = {
        'detection_class': 'detectionClass',
        'color': 'color'
    }

    def __init__(self, detection_class=None, color=None):  # noqa: E501
        """GuiDetectionColorBody - a model defined in Swagger"""  # noqa: E501
        self._detection_class = None
        self._color = None
        self.discriminator = None
        if detection_class is not None:
            self.detection_class = detection_class
        if color is not None:
            self.color = color

    @property
    def detection_class(self):
        """Gets the detection_class of this GuiDetectionColorBody.  # noqa: E501


        :return: The detection_class of this GuiDetectionColorBody.  # noqa: E501
        :rtype: DetectionClasses
        """
        return self._detection_class

    @detection_class.setter
    def detection_class(self, detection_class):
        """Sets the detection_class of this GuiDetectionColorBody.


        :param detection_class: The detection_class of this GuiDetectionColorBody.  # noqa: E501
        :type: DetectionClasses
        """

        self._detection_class = detection_class

    @property
    def color(self):
        """Gets the color of this GuiDetectionColorBody.  # noqa: E501


        :return: The color of this GuiDetectionColorBody.  # noqa: E501
        :rtype: Color
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this GuiDetectionColorBody.


        :param color: The color of this GuiDetectionColorBody.  # noqa: E501
        :type: Color
        """

        self._color = color

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GuiDetectionColorBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuiDetectionColorBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
