# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InspectionNorm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exchange_format': 'str',
        'code_system': 'str'
    }

    attribute_map = {
        'exchange_format': 'exchangeFormat',
        'code_system': 'codeSystem'
    }

    def __init__(self, exchange_format=None, code_system=None):  # noqa: E501
        """InspectionNorm - a model defined in Swagger"""  # noqa: E501
        self._exchange_format = None
        self._code_system = None
        self.discriminator = None
        if exchange_format is not None:
            self.exchange_format = exchange_format
        if code_system is not None:
            self.code_system = code_system

    @property
    def exchange_format(self):
        """Gets the exchange_format of this InspectionNorm.  # noqa: E501


        :return: The exchange_format of this InspectionNorm.  # noqa: E501
        :rtype: str
        """
        return self._exchange_format

    @exchange_format.setter
    def exchange_format(self, exchange_format):
        """Sets the exchange_format of this InspectionNorm.


        :param exchange_format: The exchange_format of this InspectionNorm.  # noqa: E501
        :type: str
        """

        self._exchange_format = exchange_format

    @property
    def code_system(self):
        """Gets the code_system of this InspectionNorm.  # noqa: E501


        :return: The code_system of this InspectionNorm.  # noqa: E501
        :rtype: str
        """
        return self._code_system

    @code_system.setter
    def code_system(self, code_system):
        """Sets the code_system of this InspectionNorm.


        :param code_system: The code_system of this InspectionNorm.  # noqa: E501
        :type: str
        """

        self._code_system = code_system

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InspectionNorm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InspectionNorm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
