# coding: utf-8

"""
    SaridaEdgeAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebHookProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_uri': 'str'
    }

    attribute_map = {
        'service_uri': 'serviceURI'
    }

    def __init__(self, service_uri=None):  # noqa: E501
        """WebHookProperties - a model defined in Swagger"""  # noqa: E501
        self._service_uri = None
        self.discriminator = None
        self.service_uri = service_uri

    @property
    def service_uri(self):
        """Gets the service_uri of this WebHookProperties.  # noqa: E501

        'The service URI for the webhook to post notifications.' '(e.g.: http://127.0.0.1:8080/uri/webHookReceiver)'   # noqa: E501

        :return: The service_uri of this WebHookProperties.  # noqa: E501
        :rtype: str
        """
        return self._service_uri

    @service_uri.setter
    def service_uri(self, service_uri):
        """Sets the service_uri of this WebHookProperties.

        'The service URI for the webhook to post notifications.' '(e.g.: http://127.0.0.1:8080/uri/webHookReceiver)'   # noqa: E501

        :param service_uri: The service_uri of this WebHookProperties.  # noqa: E501
        :type: str
        """
        if service_uri is None:
            raise ValueError("Invalid value for `service_uri`, must not be `None`")  # noqa: E501

        self._service_uri = service_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebHookProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebHookProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
